apiVersion: v1
kind: template
metadata:
    name: semantic-model-starter
    displayName: Semantic Model Starter
    description: Build a React Fabric App backed by a Power BI semantic model
    version: 0.0.1
entries:
    - name: Semantic Model Starter
      path: .
